name: Tag Environments

on:
  pull_request_review_comment:
    types: [ created, edited ]

jobs:

  docker_deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Check out GitHub repo
      # if: "!contains(github.event.head_commit.message, 'skip ci')"
      uses: actions/checkout@v2

    - name: Get Current Vars
      if: "!contains(github.event.head_commit.message, 'skip ci')"
      shell: bash
      # env:
      #   SHA: ${{ GITHUB_SHA }}
      #   REF: ${{ GITHUB_REF }}
      run: |
        export GIT_SHA=$(git rev-parse --short=7 HEAD)
        echo $(git branch)
        echo $GIT_SHA
        echo ${GITHUB_SHA}
        echo ${GITHUB_REF}

    - name: Tag That
      if: "contains(github.event.pull_request.comment, 'enable dev')"
      shell: bash
      env:
        USER: ${{ github.actor }}
        PASS: ${{ secrets.GITHUB_TOKEN }}
      #   SHA: ${{ GITHUB_SHA }}
      #   REF: ${{ GITHUB_REF }}
      run: |
        # Get name of local image to verify tagging syntax:
        # docker tag kbase/narrative:vx.y.z kbase/narrative:prod
        export GIT_SHA=$(git rev-parse --short=7 HEAD)
        docker pull docker.pkg.github.com/jsfillman/narrative/narrative:sha-$GIT_SHA
        docker login https://docker.pkg.github.com -u $USER -p $PASS
        docker tag docker.pkg.github.com/jsfillman/narrative/narrative:sha-$GIT_SHA docker.pkg.github.com/jsfillman/narrative/narrative-dev:sha-$GIT_SHA
        docker push docker.pkg.github.com/jsfillman/narrative/narrative-dev:sha-$GIT_SHA



    # - name: Retrieve version
    #   run: |
    #     export NARRATIVE_VERSION_NUM=`grep '\"version\":' src/config.json.templ | awk '{print $2}' | sed 's/"//g'`
    #     echo ::set-env name=TAG_NAME::$(cat projectFile | grep -Po '(?<=Version>).*(?=</Version>)')

    # - name: Tag Next
    #   if: "contains(github.event.head_commit.message, 'skip ci')"    
    #   uses: docker/build-push-action@v1
    #   with:
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    #     registry: docker.pkg.github.com
    #     repository: jsfillman/narrative/narrative
    #     tags: ${{ env.NARRATIVE_VERSION_NUM }},testing 
    #     tag_with_ref: true
    #     tag_with_sha: true
